### ISSUE TITLE
How to start plugin?

### ISSUE THREAD

**Issue by nt7** [Ultimaker/CuraLiveScriptingPlugin#1]
Hi,

Thank you for creating this plugin. From what I got from the description, this plugin would allow me to see & edit the generated gcode.
I am currently looking for such a feature and finding it directly included in Cura would be very useful for my workflow.

I just cannot find how to actually start the plugin/editor view. Since it registers as a tool in Cura, I thought I would get an additional square on the toolbar on the left.

Could you point me towards the right direction?

**Comment by nallath** [comment]
This plugin hasnt' been updated for some time now. Let me have a look to see if I can bump it to the latest version.

**Comment by nallath** [comment]
Should work again for 4.4: 561943ce580ca4d97dd75d27926c20b326519f12

Also; it won't make you able to change the generated g-code. It enables you to directly inject python into a running Cura instance (which is convenient for developers but not much more)

**Comment by nt7** [comment]
Awesome, thanks for taking the time!

And thanks for the description of the plugin! That makes it quite interesting for testing new plugin developments!
